services:
  web:
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - 8234:80
    environment:
      MYSQL: db
      MYSQL_USER: todo
      MYSQL_PASSWORD: todo
      MYSQL_DATABASE: todo
    depends_on:
      - db
  db:
    image: mysql:9.1
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: todo
      MYSQL_USER: todo
      MYSQL_PASSWORD: todo
  adminer:
    image: adminer
    restart: always
    ports:
      - 8412:8080
    environment:
      ADMINER_DEFAULT_SERVER: db