services:
  web:
    build: .
    ports:
      - 8234:80
    environment:
      MYSQL: db
      MYSQL_USER: todo
      MYSQL_PASSWORD: todo
      MYSQL_DATABASE: todo
    depends_on:
      - db
  db:
    image: mysql:9.1
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: todo
      MYSQL_USER: todo
      MYSQL_PASSWORD: todo